[project]
name = "candlestick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.3",
    "matplotlib>=3.10.8",
    "numpy<2.3.0",
    "pandas<3.0.0",
    "pandas-ta>=0.4.71b0",
    "pytest>=9.0.2",
    "scipy>=1.17.1",
    "stable-baselines3>=2.7.1",
    "torch>=2.10.0",
    "yfinance>=1.2.0",
]
